### ISSUE TITLE
Data-content is not being loaded

### ISSUE THREAD

**Issue by ashfrankie** [CodyHouse/schedule-template#15]
Hello,

In the demo, the data content for each event is loaded when you click on it. However, when you download the files, the content isn't loaded in the same scenario. Is this an issue with the Ajax script to grab the content? 

Thanks so much for your help!

**Comment by claudia-romano** [comment]
Hi there,
please take a look at this issue:
https://github.com/CodyHouse/schedule-template/issues/8

Cheers
