### ISSUE TITLE
Number of lines

### ISSUE THREAD

**Issue by Picpool** [CodyHouse/schedule-template#3]
When adding lines by adding LI, could i modify the LI height ?
And i need to reduce line height (if i change the 50px set in css it does not fit)
thanks

**Comment by ebichuamster** [comment]
Hi, you must set .top-info {height} .timeline li {height} .timeline {padding-top} in /css/style.css at the same value if you want that fit.

**Comment by Picpool** [comment]
Hi, thanks a lot ebichuamster  for your help !
Ad do you know if there is a way to display only 8 columns ?
thanks

**Comment by ebichuamster** [comment]
you must set .cd-schedule .events .events-group {width} at 12.5% (100%/8) or less

**Comment by Picpool** [comment]
woww thanks a lot !!!

**Comment by ebichuamster** [comment]
Welcome :yum:
