### ISSUE TITLE
Events Modal Issue

### ISSUE THREAD

**Issue by na2193** [CodyHouse/schedule-template#4]
So in the demo, when you click on an event, it pops up and shows more information. When i cloned the repo and tried to click on an event, it pops up, but does not show any more detail about it.

**Comment by ebichuamster** [comment]
Hi, you miss the end of the article : 

> One note: we implemented a simple load() function to upload the new html content, but you may wanna replace it with a $.ajax call in order to handle errors, beforeSend request etc. according to your project.

edit the line 119 in js/main.js according to your project.

**Comment by na2193** [comment]
thanks
