### ISSUE TITLE
Two Events that overlap on a same timestamp

### ISSUE THREAD

**Issue by WithBaconPlz** [CodyHouse/schedule-template#6]
When you have two events overlapping, only the latest created takes the spot. How would it be possible to have the width of these events divided by 2 and have them both appear on the schedule.

**Comment by Thrasher-1** [comment]
I had the same issue just-now and came up with inline styling
event 1 of the same time, I put: **style="width:50%"**
event 2 of the same time, I put: **style="width:50%; margin-left:50%"**
and it worked like a charm! (even changed the colors to accommodate the difference) 
Problem now is > There isn't very much room for text! (((blech)))

**Comment by claudia-romano** [comment]
Hi there, we do not have such an option. The layout was planned for having one event only at a time. If you need to have two, @Thrasher-1 solution should do it.
