### ISSUE TITLE
Events after 18:00

### ISSUE THREAD

**Issue by funkynick** [CodyHouse/schedule-template#7]

**Comment by funkynick** [comment]
Sorry for my empty comment )

I have an issue with adding events which have timeline after 18:00.
How can i fix this? For example event with 19:00 start and 20:30 end, doesn't display correctly (

**Comment by claudia-romano** [comment]
Hi there, we have just released a new version (2.0) of this experiment (based on the [CodyHouse framework](https://codyhouse.co/ds/docs/framework)).

With this new version, you will need to update the --schedule-rows-number css variable in the style.scss file as well as include a new list item inside the .cd-schedule__timeline element in the index.html file. 

So for example, if you want to show events displaying till 20:30, you will need to add 5 new list items in the .cd-schedule__timeline and update --schedule-rows-number from 19 to 24.
