### ISSUE TITLE
event popup text not loading

### ISSUE THREAD

**Issue by aukevanheel** [CodyHouse/schedule-template#8]
I downloaded it as it is and I noticed that the data from the event HTML files is not loading as in the live example.... anyone has a clue why it is not loading?

thanks in advance

**Comment by waqid** [comment]
Maybe it has been blocked by CORS policy. Please use localhost / real server in order open up event popup properly.

**Comment by claudia-romano** [comment]
Hi there, the issue is exactly the one @waqid described. 
Make sure to use a local server and you won't be experiencing this issue anymore.
