### ISSUE TITLE
Limit At Timelline

### ISSUE THREAD

**Issue by berrabe** [CodyHouse/schedule-template#9]
oke, default timeline is from 09.00 to 18.00
but when i add 18.30 and 19.00... 
there is just horizontal line on events table and NO VERTICAL LINE

![schedule template codyhouse - google chrome_003](https://user-images.githubusercontent.com/34432326/53566818-ecc1d980-3b8f-11e9-9174-0609151f8f4a.png)

**Comment by claudia-romano** [comment]
Hi there, we have just released a new version (2.0) of this experiment (based on the [CodyHouse framework](https://codyhouse.co/ds/docs/framework)).

With this new version, you will need to update the --schedule-rows-number css variable in the style.scss file (as you added two new slots, you should change the value from 19 to 21). This will fix your issue.
